[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="JetBrainsMono Nerd Font"
FontSize="12"

KeyboardSize="0.4"

RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/battery.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.35"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors (Catppuccin Mocha) ####################

HeaderTextColor="#cdd6f4"
DateTextColor="#cdd6f4"
TimeTextColor="#cdd6f4"

FormBackgroundColor="#1e1e2e"
BackgroundColor="#1e1e2e"
DimBackgroundColor="#1e1e2e"

LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"
LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"
UserIconColor="#cdd6f4"
PasswordIconColor="#cdd6f4"

PlaceholderTextColor="#a6adc8"
WarningColor="#f38ba8"

LoginButtonTextColor="#1e1e2e"
LoginButtonBackgroundColor="#cba6f7"
SystemButtonsIconsColor="#cdd6f4"
SessionButtonTextColor="#cdd6f4"
VirtualKeyboardButtonTextColor="#cdd6f4"

DropdownTextColor="#cdd6f4"
DropdownSelectedBackgroundColor="#45475a"
DropdownBackgroundColor="#313244"

HighlightTextColor="#1e1e2e"
HighlightBackgroundColor="#cba6f7"
HighlightBorderColor="transparent"

HoverUserIconColor="#89b4fa"
HoverPasswordIconColor="#89b4fa"
HoverSystemButtonsIconsColor="#89b4fa"
HoverSessionButtonTextColor="#89b4fa"
HoverVirtualKeyboardButtonTextColor="#89b4fa"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="false"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="true"
HideLoginButton="true"

UseRealName="true"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
